version: "3"
services:
  odoo:
    image: adrianchang/kenny-odoo:8.0
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - odoo-web-data:/var/lib/odoo
      # - openerp-server.conf:/etc/odoo/openerp-server.conf:ro
      - ./:/mnt/extra-addons:ro

  db:
    image: postgres:11.6
    env_file:
      - .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env

volumes:
  odoo-web-data:
  odoo-db-data:
